# Configurazione per l'autenticazione
auth:
  credentials_path: 'credentials/web_credentials.json'  
  token_path: 'credentials/token.pickle'
  headless: true
  port: 8080

# Cartelle da sincronizzare
# Formato: percorso_google_drive: percorso_locale
sync_folders:
  'test_poc_drive/cartella_test_1': './test_poc_drive/cartella_test_1'
  'test_poc_drive/cartella_test_2': './test_poc_drive/cartella_test_2'

# Preferenze di sincronizzazione
preferences:
  conflict_resolution: 'drive'
  enable_deletion: false
  min_sync_interval: 60
  exclusions:
    - '*.tmp'
    - '.DS_Store'
    - 'Thumbs.db'